#!/bin/sh


print_help() {
    echo "usage: $0 <path> <ssh_args>"
    echo ""
    echo "Create snapshots on remote host, pull them into current directory, add them to snapshots.tsv"
}

if [ $# -lt 2 ]; then
    print_help >&2
    exit 1
fi

SUBVOL="$1"
shift

ssh $* friclone-snapshot "${SUBVOL}"
SNAPTAB=$(ssh $* friclone-send "${SUBVOL}" latest)

IFS='
'

for LINE in SNAPTAB; do
    L_SNAPUUID=$(echo "${LINE}" | cut -d'	' -f 3)
    L_SNAP=$(echo "${LINE}" | cut -d'	' -f 4)
    L_SUBSUBVOL=$(echo "${LINE}" | cut -d'	' -f 5)
    if ssh $* friclone-send ${SUBVOL} ${L_SNAP} ${L_SUBSUBVOL} > ${L_SNAPUUID}.zstd; then
        echo "${LINE}" >> snapshots.tsv
    else
        echo "FAILED TO GET ${L_SNAP}/${L_SUBSUBVOL}" >&2
    fi
done
