#!/bin/sh


print_help() {
    echo "usage: $0 <path> <clean|name|remove|prune> [snapshot] [name]"
    echo ""
    echo "Manage snapshots"
    echo "  clean - remove backups"
    echo "  name - name a snapshot for easier access"
    echo "  prune - remove all snapshots without names"
    echo "  remove - remove a snapshot (or name)"
    echo "  unbackup - change a backup into a snapshot"
    echo ""
    echo "  "
}

if [ $# -lt 2 ]; then
    print_help >&2
    exit 1
fi

SUBVOL="$1"
CMD="$2"
SNAP="$3"
NAME="$4"

# save current dir
_PWD=$(pwd)

# get filesystem UUID. If someone can fix this, please, do!
FS_UUID=$(blkid -s UUID -o value $(btrfs filesystem usage "${SUBVOL}" | grep -o "/dev/[^ ]*" | tail -n -1)) || { echo "Can not determine filesystem UUID" >&2; exit 1; }

# create dirs
mkdir /run/friclone 2> /dev/null
ROOTMNT=/run/friclone/$FS_UUID
mkdir "${ROOTMNT}" 2> /dev/null

# mount the root filesystem containing the volume to be enrolled
mount -o subvol=/ /dev/disk/by-uuid/$FS_UUID "${ROOTMNT}"

# create friclone directories
FRICL=/run/friclone/$FS_UUID/.friclone
if ! [ -e "${FRICL}" ]; then
    btrfs subvol create "${FRICL}"
fi

SNAPDIR="$FRICL/snapshots/${FS_UUID}"

case "${CMD}" in
    clean)
        for d in "${FRICL}/backup/${FS_UUID}/*"; do
            # if the volume is mounted, skip
            vol_id=$(btrfs inspect-internal rootid "${d}")
            safe=""
            for dev in $(mount -t btrfs | cut -d ' ' -f 1,6 | grep "[(,]subvolid=${vol_id}[,)]" | cut -d " " -f 1); do
                if [ $(blkid "${dev}") = "${FS_UUID}" ]; then
                    safe="no"
                fi
            done
            if [ -z "${safe}" ]; then
                echo btrfs subvolume delete -R "${d}"
            fi
        done
        ;;
    name)
        ln -r -sf "${SNAPDIR}/${SNAP}" "${SNAPDIR}/${NAME}"
        ;;
    prune)
        mkdir ${FRICL}/tmpkeep 2> /dev/null
        TMPKEEP=${FRICL}/tmpkeep/${FS_UUID}
        if [ -d "${TMPKEEP}" ]; then
            echo "${TMPKEEP} exists - is another prune running?" >&2
        else
            mkdir ${TMPKEEP} 2> /dev/null
            cd "${SNAPDIR}"
            for i in *; do
                if [ -L $i ]; then
                    mv "$(readlink $i)" "${TMPKEEP}"
                    mv "$i" "${TMPKEEP}"
                fi
            done
            for i in *; do
                btrfs subvolume delete -R "$i"
            done
            mv ${TMPKEEP}/* .
            rmdir ${TMPKEEP}
        fi
        ;;
    remove)
        if [ -z "${SNAP}" ]; then
            ls "${SNAPDIR}"
        elif [ -L "${SNAPDIR}/${SNAP}" ]; then
            rm "${SNAPDIR}/${SNAP}";
        elif [ -d "${SNAPDIR}/${SNAP}" ]; then
            btrfs subvolume delete -R "${SNAPDIR}/${SNAP}/*/snapshot"
            rm -rf "${SNAPDIR}/${SNAP}"
        else
            ls "${SNAPDIR}"
        fi
        ;;
    unbackup)
        if [ -z "${SNAP}" ] || ! [ -d "${FRICL}/backup/${FS_UUID}/${SNAP}" ]; then
            ls "${FRICL}/backup/${FS_UUID}"
        else
            cd "${FRICL}/backup/${FS_UUID}/${SNAP}"
            for i in *; do 
                btrfs subvolume snapshot -r $i/snapshot ${SNAPDIR}/${DATE}/snapshot
                btrfs subvolume delete $i/snapshot
                mv $i/link ${SNAPDIR}/${DATE}
            done
        fi
        ;;
    *)
        print_help
        ;;    
esac

# return to old dir
cd "$_PWD"

# cleanup
umount "$ROOTMNT" && rmdir "$ROOTMNT"
rmdir /run/friclone
