#!/bin/sh


print_help() {
    echo "usage: $0 <path> <snapshot>"
    echo ""
    echo "Restore state from snapshot"
    echo "  Restores the volumes preserved in a snapshot of <path>."
    echo "  If <snapshot> is not specified, list snapshots."
}

if [ $# -lt 1 ]; then
    print_help >&2
    exit 1
fi

SUBVOL="$1"
SNAP="$2"

# save current dir
_PWD=$(pwd)

# get filesystem UUID. If someone can fix this, please, do!
FS_UUID=$(blkid -s UUID -o value $(btrfs filesystem usage "${SUBVOL}" | grep -o "/dev/[^ ]*" | tail -n -1)) || { echo "Can not determine filesystem UUID" >&2; exit 1; }

# create dirs
mkdir /run/friclone 2> /dev/null
ROOTMNT=/run/friclone/$FS_UUID
mkdir "${ROOTMNT}" 2> /dev/null

# mount the root filesystem containing the volume to be enrolled
mount -o subvol=/ /dev/disk/by-uuid/$FS_UUID /run/friclone/$FS_UUID

# create friclone directories
FRICL=/run/friclone/$FS_UUID/.friclone
if ! [ -e "${FRICL}" ]; then
    btrfs subvol create "${FRICL}"
fi

SRCPATH="$FRICL/snapshots/${FS_UUID}/${SNAP}"
if [ ! -z ${SNAP} ] && [ -d "${SRCPATH}" ]; then
    DATE=$(date -u -Is)
    BACKUP="${FRICL}/backup"
    mkdir "${BACKUP}" 2> /dev/null
    BACKUP="${BACKUP}/${FS_UUID}"
    mkdir "${BACKUP}" 2> /dev/null
    BACKUP="${BACKUP}/${DATE}"
    mkdir "${BACKUP}" 2> /dev/null

    if cd "${SRCPATH}"; then
        for i in $(ls | sort); do
            # skip ../../../ - 9 characters
            vol=$(readlink "${i}/link" | cut -c 10-)
            mv "${ROOTMNT}/${vol}" "${BACKUP}/${i}/snapshot"
            cp "${i}/link" "${BACKUP}/${i}/link"
            btrfs subvol snapshot "${i}/snapshot" "${ROOTMNT}/${vol}"
        done
    else
        echo "No subvolumes enrolled. Maybe use friclone-enroll?" >&2
    fi
else
    cd $FRICL/snapshots/${FS_UUID}
    ls
fi

# return to old dir
cd "$_PWD"

# cleanup
umount "$ROOTMNT" && rmdir "$ROOTMNT"
rmdir /run/friclone
