#!/bin/sh


print_help() {
    echo "usage: $0 <path>"
    echo ""
    echo "Snapshot path."
    echo "  Creates a snapshot of all enrolled volumes for the filesystem containing <path>."
}

cleanup() {
    # return to old dir
    [ -z "$_PWD" ] && cd "$_PWD"
    # cleanup
    [ -z "${ROOTMNT}" ] && umount "${ROOTMNT}" && rmdir "${ROOTMNT}"
    rmdir /run/friclone
}

if [ $# -lt 1 ]; then
    print_help >&2
    exit 1
fi

SUBVOL="$1"

trap cleanup SIGHUP SIGINT SIGQUIT SIGKILL SIGALRM SIGTERM EXIT

# save current dir
_PWD=$(pwd)

# get filesystem UUID. If someone can fix this, please, do!
FS_UUID=$(blkid -s UUID -o value $(btrfs filesystem usage "${SUBVOL}" | grep -o "/dev/[^ ]*" | tail -n -1)) || { echo "Can not determine filesystem UUID" >&2; exit 1; }

# create mount dirs
ROOTMNT=/run/friclone/$FS_UUID
mkdir -p "${ROOTMNT}" 2> /dev/null

# mount the root filesystem containing the volume to be enrolled
mount -o subvol=/ /dev/disk/by-uuid/$FS_UUID /run/friclone/$FS_UUID

# create friclone directories
FRICL=/run/friclone/$FS_UUID/.friclone
[ -e "${FRICL}" ] || btrfs subvol create "${FRICL}"

SNAPDIR="$FRICL/snapshots/${FS_UUID}"
DATE=$(date -u -Is)
DESTPATH="${SNAPDIR}/${DATE}"
mkdir -p "${DESTPATH}" 2> /dev/null

LINKPATH="$FRICL/subvolumes/$FS_UUID/"
if cd $LINKPATH; then 
    for i in $(ls | sort); do
        if vol=$(readlink $i); then
            echo "snapshot ${vol} -> ${DESTPATH}/${i}/snapshot"
            mkdir "${DESTPATH}/${i}"
            cp -d $i "${DESTPATH}/${i}/link"
            btrfs subvol snapshot -r "${vol}" "${DESTPATH}/${i}/snapshot"
        fi
    done
else
    echo "No subvolumes enrolled. Maybe use friclone-enroll?" >&2
    exit 1
fi

rm "${SNAPDIR}/latest" 2> /dev/null
ln -srf "${DESTPATH}" "${SNAPDIR}/latest"

