#!/bin/sh


print_help() {
    echo "usage: $0 <path> [name] [remove]"
    echo ""
    echo "Add subvolume to the list to be snapshotted or restored."
    echo "  if [name] is not specified, list the volumes."
    echo "  <path> must be a BTRFS subvolume."
    echo "  [name] is used to determine the order of restore."
    echo '  if the third argument is "remove", un-enroll the path.'
}

if [ $# -lt 1 ]; then
    print_help >&2
    exit 1
fi

SUBVOL="$1"
NAME="$2"

# assert the directory is a btrfs subvolume,
# determine the path of the subvolume relative to root
if INFO=$(btrfs subvol show "${SUBVOL}" 2>/dev/null ); then
    SUBVOLPATH=../../../$(echo "${INFO}" | head -n 1)
else
    if [ "$3" != "remove" ]; then
        echo "The <path> must be a BTRFS subvolume, ${SUBVOL} is not!" >&2
        exit 1
    fi
fi

# save current dir
_PWD=$(pwd)

# get filesystem UUID. If someone can fix this, please, do!
FS_UUID=$(blkid -s UUID -o value $(btrfs filesystem usage "$1" | grep -o "/dev/[^ ]*" | tail -n -1))

# create dirs
mkdir /run/friclone 2> /dev/null
ROOTMNT=/run/friclone/$FS_UUID
mkdir "${ROOTMNT}" 2> /dev/null

# mount the root filesystem containing the volume to be enrolled
mount -o subvol=/ /dev/disk/by-uuid/$FS_UUID /run/friclone/$FS_UUID

# create friclone directories
FRICL=/run/friclone/$FS_UUID/.friclone
if ! [ -e "${FRICL}" ]; then
    btrfs subvol create "${FRICL}"
fi
mkdir "${FRICL}/subvolumes" 2> /dev/null
mkdir "${FRICL}/subvolumes/${FS_UUID}" 2> /dev/null

# where the symlink will be
LINKPATH="$FRICL/subvolumes/$FS_UUID/"
cd $LINKPATH

if [ $# -lt 2 ]; then
    for i in $(ls | sort); do
        # skip ../../../ - 9 characters
        echo -n $i " "; readlink $i | cut -c 10-
    done
elif [ "$3" = "remove" ]; then
    rm "${NAME}"
else
    ! test -L "${NAME}" || rm "${NAME}"
    ln -sf "${SUBVOLPATH}" "${NAME}"
fi
# return to old dir
cd "$_PWD"

# cleanup
umount "$ROOTMNT" && rmdir "$ROOTMNT"
rmdir /run/friclone
