#!/bin/sh


print_help() {
    echo "usage: $0 <path> <snapshot> [subvol]"
    echo ""
    echo "Send snapshot"
    echo "  If <snapshot> is not specified, list snapshots and their links."
    echo "  Without [subvol], list subvolumes and where they point to."
    echo "  If [subvol] is specified and exists, output a zstd compressed snapshot."
    echo ""
    echo "If any snapshots named sent-* exist, use them as clone sources when sending the snapshot."
    echo "Creates a snapshot name called sent-DATE on success."
}

if [ $# -lt 1 ]; then
    print_help >&2
    exit 1
fi

SUBVOL="$1"
SNAP="$2"
SUBSUBVOL="$3"

# save current dir
_PWD=$(pwd)

# get filesystem UUID. If someone can fix this, please, do!
FS_DEV=$(realpath $(btrfs filesystem usage "${SUBVOL}" | grep -o "/dev/[^ ]*" | tail -n -1))
FS_UUID=$(blkid -s UUID -o value "${FS_DEV}") || { echo "Can not determine filesystem UUID" >&2; exit 1; }
for i in /dev/disk/by-partuuid/*; do
    [ "${FS_DEV}" = "$(realpath $i)" ] && FS_PARTUUID=$(basename $i);
done

# create dirs
mkdir /run/friclone 2> /dev/null
ROOTMNT=/run/friclone/$FS_UUID
mkdir "${ROOTMNT}" 2> /dev/null

# mount the root filesystem containing the volume to be enrolled
mount -o subvol=/ /dev/disk/by-uuid/$FS_UUID /run/friclone/$FS_UUID

# create friclone directories
FRICL=/run/friclone/$FS_UUID/.friclone
if ! [ -e "${FRICL}" ]; then
    btrfs subvol create "${FRICL}"
fi

SRCPATH="$FRICL/snapshots/${FS_UUID}/${SNAP}"
if [ ! -z "${SNAP}" ] && [ -d "${SRCPATH}" ]; then
    if cd "${SRCPATH}"; then
        # always symlink to snapshots, not their names
        [ -L "${SRCPATH}" ] && SNAP=$(readlink "${SRCPATH}")
        if [ ! -z "${SUBSUBVOL}" ] && [ -d "${SRCPATH}/${SUBSUBVOL}" ]; then
            # prepare symlink dirs
            mkdir "${SENTDIR}" 2> /dev/null
            SENTDIR="${FRICL}/sent/${FS_UUID}"
            mkdir "${SENTDIR}" 2> /dev/null
            # read previously sent snapshots of the same volume
            parents=""
            for parent in "${SENTDIR}/${SUBSUBVOL}-"*/snapshot; do
                [ -e $parent ] && parents="${parents} -c "$(realpath "${parent}")
            done
            SENTLINK=${SENTDIR}/${SUBSUBVOL}-${SNAP}
            if [ -e "${SENTLINK}" ] || [ -L "${SENTLINK}" ]; then
                echo "Refuse to send snapshot more than once" >&2;
            else
                # SEND SNAPSHOT AND CREATE SYMLINK IN sent
                echo btrfs send --proto 0${parents} ${SRCPATH}/${SUBSUBVOL}/snapshot >&2
                { 
                    btrfs send --proto 0${parents} ${SRCPATH}/${SUBSUBVOL}/snapshot &&\
                        ln -r -s "${SRCPATH}/${SUBSUBVOL}" "${SENTLINK}" > /dev/null
                } | zstd -z --stdout
            fi
        else
            # list the links / subsubvolumes in a snapshot
            for i in $(ls | sort); do
                SNAP_INFO=$(btrfs subvolume show $i/snapshot)
                SNAP_UUID=$(echo "${SNAP_INFO}" | sed -n -e '/^[[:space:]]*UUID:/s/.*UUID:[[:space:]]*\([a-z0-9-]*\).*$/\1/p')
                SNAP_RECVUUID=$(echo "${SNAP_INFO}" | sed -n -e '/^[[:space:]]*Received UUID:/s/.*UUID:[[:space:]]*\([a-z0-9-]*\).*$/\1/p')
                if [ "${SNAP_RECVUUID}" = "-" ] || [ -z ${SNAP_RECVUUID}]; then
                    SHOW_UUID="${SNAP_UUID}"
                else
                    SHOW_UUID="${SNAP_RECVUUID}"
                fi
                echo -n "${FS_UUID}\t${FS_PARTUUID}\t${SHOW_UUID}\t${SNAP}/${i}\t"; readlink "${i}/link"
            done
        fi
    else
        echo "No subvolumes enrolled. Maybe use friclone-enroll?" >&2
    fi
else
    [ -z "${SNAP}" ] && ls "${SRCPATH}"
fi

# return to old dir
cd "$_PWD"

# cleanup
umount "$ROOTMNT" && rmdir "$ROOTMNT"
rmdir /run/friclone
