#!/bin/sh

print_help() {
    echo "usage: $0 <path> [URL] [remember|forget]"
    echo ""
    echo "Receive snapshots from remote"
    echo ""
    echo "If \"remember\" is added after the URL and the retreival of snapshots is successfull,"
    echo "the URL will be stored in the config."
    echo "If \"forget\" is added, the URL will be removed from the repos."
}

if [ $# -lt 1 ]; then
    print_help >&2
    exit 1
fi

SUBVOL="$1"
URL="$2"
URL_ACTION="$3"

# save current dir
_PWD=$(pwd)

# get filesystem UUID. If someone can fix this, please, do!
FS_DEV=$(realpath $(btrfs filesystem usage "${SUBVOL}" | grep -o "/dev/[^ ]*" | tail -n -1))
FS_UUID=$(blkid -s UUID -o value "${FS_DEV}") || { echo "Can not determine filesystem UUID" >&2; exit 1; }
for i in /dev/disk/by-partuuid/*; do
    [ "${FS_DEV}" = "$(realpath $i)" ] && FS_PARTUUID=$(basename $i);
done

# create dirs
mkdir /run/friclone 2> /dev/null
ROOTMNT=/run/friclone/$FS_UUID
mkdir "${ROOTMNT}" 2> /dev/null

# mount the root filesystem containing the volume to be enrolled
mount -o subvol=/ /dev/disk/by-uuid/$FS_UUID /run/friclone/$FS_UUID

# create friclone directories
FRICL=/run/friclone/$FS_UUID/.friclone
if ! [ -e "${FRICL}" ]; then
  btrfs subvol create "${FRICL}"
fi

get_data() {
    set -e
    URL=$1
    SCHEMA=$(echo $URL | sed -e 's!\([^:]*\)://\(.*\)!\1!')
    SRC=$(echo $URL | sed -e 's!\([^:]*\)://\(.*\)!\2!')
    case "${SCHEMA}" in
        file)
            cat "${SRC}"
            ;;
        *)
            wget -q -O - "${URL}"
            ;;
    esac
}

SNAPDIR="${FRICL}/snapshots/${FS_UUID}"

IFS="\n"
SNAPSHOTS=""
if [ "${URL_ACTION}" = "forget" ] then
    cat "${FRICL}/repos.txt" | grep -v "^${URL}\$" > "${FRICL}/repos.txt"
    exit 0;
elif [ -z "${URL}" ] then
    if URLLIST=$(cat ${FRICL}/repos.txt); then
        SUCCESS="true"
    fi
else
    URLLIST="${URL}";
    SUCCESS="true"
fi

for URL_I in ${URLLIST}; do
    if SNAPS_I=$(get_data "${URL}/snapshots.tsv"); then
        SNAPSHOTS="${SNAPS_I}"
        URL="${URL_I}"
        break
    else
        echo "Failed to fetch ${URL_I}/snapshots.tsv" >&2
    fi
done

for LINE in ${SNAPSHOTS}; do
    echo ${LINE}
    L_FSUUID=$(echo "${LINE}" | cut -d$'\t' -f 1)
    L_PARTUUID=$(echo "${LINE}" | cut -d$'\t' -f 2)
    if [ "${L_PARTUUID}" = "${FS_PARTUUID}"] || [ "${L_FSUUID}" = "${FS_UUID}" ]; then
        L_SNAPUUID=$(echo "${LINE}" | cut -d$'\t' -f 3)
        L_SNAP=$(echo "${LINE}" | cut -d$'\t' -f 4)
        L_SUBSUBVOL=$(echo "${LINE}" | cut -d$'\t' -f 5)
        L_LINK=$(echo "${LINE}" | cut -d$'\t' -f 6-)
        L_SNAPPATH=${SNAPDIR}/${L_SNAP}/${L_SUBSUBVOL}/
        mkdir "${SNAPDIR}/${L_SNAP}" 2> /dev/null
        mkdir "${SNAPDIR}/${L_SNAP}/${L_SUBSUBVOL}" 2> /dev/null
        if [ -e "${SNAPDIR}/${L_SNAP}/${L_SUBSUBVOL}/link" ]; then
            if [ $(readlink "${SNAPDIR}/${L_SNAP}/${L_SUBSUBVOL}/link") != "$L_LINK" ]; then
                echo "Link exists but points to a different path!" >&2;
                rm "${SNAPDIR}/${L_SNAP}/${L_SUBSUBVOL}/link"
            fi
        fi
        # receive link
        ln -sf "${L_SNAPPATH}/link" "${L_LINK}" || SUCCESS=false
        SKIP_RECV="false"
        if [ -e "${L_SNAPPATH}/snapshot" ]; then
            SNAP_INFO=$(btrfs subvolume show "${L_SNAPPATH}/snapshot")
            SNAP_UUID=$(echo "${SNAP_INFO}" | sed -n -e '/^[[:space:]]*UUID:/s/.*UUID:[[:space:]]*\([a-z0-9-]*\).*$/\1/p')
            SNAP_RECVUUID=$(echo "${SNAP_INFO}" | sed -n -e '/^[[:space:]]*Received UUID:/s/.*UUID:[[:space:]]*\([a-z0-9-]*\).*$/\1/p')
            if [ "${SNAP_RECVUUID}" = "-" ] || [ -z ${SNAP_RECVUUID}]; then
                SHOW_UUID="${SNAP_UUID}"
            else
                SHOW_UUID="${SNAP_RECVUUID}"
            fi
            if [ "${SHOW_UUID}" != "${L_SNAPUUID}" ]; then
                echo "UUIDs do not match, deleting old snapshot" >&2
                btrfs subvolume delete "${L_SNAPPATH}/snapshot"
            else
                SKIP_RECV="true"
            fi
        fi
        if [ "${SKIP_RECV}" != "true" ]; then
            get_data "${URL}/${L_FSUUID}.zstd" | zstd -d | btrfs receive "${L_SNAPPATH}/snapshot" || SUCCESS=false
        fi
    fi
done

if [ "${URL_ACTION}" = "remember" ] && [ ${SUCCESS} = "true" ] then
    echo "${URL}" >> "${FRICL}/repos.txt"
    echo "Repos now:"
    cat "${FRICL}/repos.txt"
fi

# return to old dir
cd "$_PWD"

# cleanup
#umount "$ROOTMNT" && rmdir "$ROOTMNT"
#rmdir /run/friclone
