#!/bin/sh


print_help() {
    echo "usage: $0 <path> <ssh_args>"
    echo ""
    echo "Create snapshots on remote host, pull them into current directory, add them to snapshots.tsv"
}

if [ $# -lt 2 ]; then
    print_help >&2
    exit 1
fi

SUBVOL="$1"
shift

#if ! ssh $* friclone snapshot "${SUBVOL}"; then
#    echo "friclone snapshot ${SUBVOL} failed!"
#fi

if ! SNAPTAB=$(ssh $* friclone send "${SUBVOL}" latest); then
    SNAPTAB=""
    echo "friclone send ${SUBVOL} latest failed!" >&2
fi

if ! [ -e snapshots.tsv ]; then
    echo "${SNAPTAB}" | head -n 1 > snapshots.tsv
fi

SNAPTAB=$(echo "${SNAPTAB}" | tail -n +2)

IFS='
'

for LINE in ${SNAPTAB}; do
    L_SNAPUUID=$(echo "${LINE}" | cut -s -d'	' -f 2)
    L_SNAP=$(echo "${LINE}" | cut -s -d'	' -f 3)
    L_SUBSUBVOL=$(echo "${LINE}" | cut -s -d'	' -f 4)
    if [ -z "${L_SNAPUUID}" ] || [ -z "${L_SNAP}" ] || [ -z "$L_SUBSUBVOL" ]; then
        continue
    fi
    echo ssh $* friclone send "${SUBVOL}" "${L_SNAP}" "${L_SUBSUBVOL}"
    if ssh $* friclone send "${SUBVOL}" "${L_SNAP}" "${L_SUBSUBVOL}" > "${L_SNAPUUID}.zstd"; then
        echo "${LINE}" >> snapshots.tsv
    else
        echo "FAILED TO GET ${L_SNAP}/${L_SUBSUBVOL}" >&2
    fi
done
