#!/bin/sh

# after cloning the home folder with home_clone, fixes weirdness and strings 
# that should refer to the current user and not the proto user

PAM_USER=$1

PROTO_HOME_STRING="/home/asistent"
PROTO_USER="asistent"
PROTO_GROUP="asistent"

PASS_ENT=$(getent passwd "${PAM_USER}")
ORIG_UID=$(getent passwd "${PROTO_USER}" | cut -s -d: -f3)

HOME=$(echo "${PASS_ENT}" | cut -s -d: -f6)
REMOTE_HOME=$(echo "${HOME}" | sed -e s:/home/:/remote_home/: )
UID=$(echo "${PASS_ENT}" | cut -s -d: -f3)
FULL_USER=$(echo "${PASS_ENT}" | cut -s -d: -f1)

SNAPSHOT_PREFIX=/home/home_snapshots/$UID
FIX_PREFIX=/usr/local/share/home_clone

IFS="
"

# fix textual references to the home directory
for fpath in $(cat "${FIX_PREFIX}/fixhome"); do
  for i in ${SNAPSHOT_PREFIX}/${fpath}; do
    echo "Fixing home for $i"
    # echo sed -i "s:${PROTO_HOME_STRING}:${HOME}:" "${i}";
    [ -e "${i}" ] && sed -i "s:${PROTO_HOME_STRING}:${HOME}:g" "${i}";
  done
done


# fix symbolic links to the home directory
for fpath in $(cat "${FIX_PREFIX}/fixlinks"); do
  for i in ${SNAPSHOT_PREFIX}/${fpath}; do
    echo "Fixing symlinks for $i"
    if [ -L "${i}" ]; then
      target=$(readlink "${i}" | sed -e "s:${PROTO_HOME_STRING}:${HOME}:g") 
      ln -sfn "${target}" "${i}"
      chown -h "${ORIG_UID}":"${ORIG_UID}" "${i}"
      if ! [ -e "${i}" ]; then
        echo "    removing $i"
        rm ${i}
      fi
      # echo ln -sfn "${target}" "${i}"
    fi
  done
done

# Wine-specific: rename the user's home inside the default Wine prefix
mv "${PREFIX}/.wine/drive_c/users/${PROTO_USER}" "${PREFIX}/.wine/drive_c/users/${FULL_USER}"
