#!/bin/sh

# clone the home of proto user to the current Samba/AD user home,
# set up correct permissions and fix any specific problems with home_clone_fix

PAM_USER=$1

PROTO_HOME="/home/asistent"
PROTO_USER="asistent"
PROTO_GROUP="asistent"

SNAPSHOT_HOME_BASE="/home/home_snapshots"

PASS_ENT=$(getent passwd ${PAM_USER})
ORIG_UID=$(getent passwd ${PROTO_USER} | cut -s -d: -f3)
ORIG_GID=$(getent passwd ${PROTO_GROUP} | cut -s -d: -f4)

HOME=$(echo "${PASS_ENT}" | cut -s -d: -f6)
# location of the Samba mounted home
REMOTE_HOME=$(echo "${HOME}" | sed -e s/\\/home\\//\\/remote_home\\// )
UID=$(echo "${PASS_ENT}" | cut -s -d: -f3)
GID=$(echo "${PASS_ENT}" | cut -s -d: -f4)

FULL_USER=$(echo "${PASS_ENT}" | cut -s -d: -f1)

# echo "-----" 
# echo "TEST FOR ${REMOTE_HOME}" 
#if test -d "${REMOTE_HOME}"; then
#        echo "XCREATING /local_home/${UID}" 
#fi

# /usr/local/bin/home_clone_clean

# proceed if user is either "student" or a remote user (Samba, AD etc.) 
if test "${UID}" -gt 1100 || test "${PAM_USER}" = "student"; then
	SNAPSHOT_HOME="${SNAPSHOT_HOME_BASE}/${UID}" 
    # place snapshot in a known location
	if ! test -d "${SNAPSHOT_HOME}"; then
		btrfs subvolume snapshot ${PROTO_HOME} "${SNAPSHOT_HOME}"
	fi
    # create user home if it doesn't exist yes
	if ! test -e "${HOME}"; then
		mkdir "${HOME}"
	fi
	if ! mountpoint -q "${HOME}"; then
		#echo mount -o bind -o "X-mount.idmap=u:${ORIG_UID}:${UID}:1 g:${ORIG_UID}:${GID}:1" "${SNAPSHOT_HOME}" "${HOME}"
		mount -o bind -o "X-mount.idmap=u:${ORIG_UID}:${UID}:1 g:${ORIG_GID}:${GID}:1 u:0:0:999 g:0:0:999" "${SNAPSHOT_HOME}" "${HOME}"
		if test "${UID}" -gt 1100; then
			# su "${PAM_USER}" -c "ls \"${REMOTE_HOME}\""
        
            # the prototype home has symlinks to ${SNAPSHOT_HOME}/home_share, 
            # so user's preferences don't get overwritten
			if setpriv --reuid="${UID}" --regid="#{GID}" test -e "${REMOTE_HOME}"; then
				mv "${SNAPSHOT_HOME}/home_share" "${SNAPSHOT_HOME}/proto_home_share"
                ln -s "${REMOTE_HOME}" "${SNAPSHOT_HOME}/home_share"
				chown -h $PROTO_USER:$PROTO_GROUP "${SNAPSHOT_HOME}/home_share" 
			else
				echo "${REMOTE_HOME} does not exist!"
			fi
		fi
		home_clone_fix ${UID}
	fi
fi
