#!/bin/sh

LOGIN_JSON=$(loginctl -j list-users)

PROTO_HOME="/home/asistent"
PROTO_USER="asistent"
PROTO_GROUP="asistent"

SNAPSHOT_HOME_BASE="/home/home_snapshots"
ADMIN_HOME="/home/local_admin"

KEEP_UIDS=$(echo ${LOGIN_JSON} | jq -r 'map(.uid) | join("\t")')
KEEP_UIDS="${KEEP_UIDS}\t0"

for homedir in /home/*; do
    if [ "$homedir" != "$PROTO_HOME" ] && [ "$homedir" != "$SNAPSHOT_HOME_BASE" ] && [ "$homedir" != "$ADMIN_HOME" ]; then
        UID=$(stat -c "%u" "${homedir}")
        if echo "${KEEP_UIDS}" | grep -w -q "${UID}"; then
            # echo "Don't recursively umount ${UID}"
            true
        else
            umount --recursive "${homedir}";
            rmdir "${homedir}"
        fi
    fi
done

[ ! -d /home/home_snapshots ] && mkdir /home/home_snapshots
cd /home/home_snapshots
for snapshot in $(ls); do
	if echo "${KEEP_UIDS}" | grep -w -q "${snapshot}"; then
		# echo "Keep ${snapshot}"
		true
	else
		# echo $snapshot
		btrfs subvol del "${snapshot}" 2> /dev/null > /dev/null;
	fi
done
